### PR TITLE
Added list of plugins and quick usage tips to readme

### PR DESCRIPTION
**Pull request by nbelakovski**
I was looking for something like this in order to understand what my vim had been transformed into and what are all the new toys I could play with, so I made it myself.

A couple of questions, like:
-is ludwig/split-man-page necessary? Seems redundant with jedi-vim
-vim-bootstrap-updated - should I bother including this? Seems like a work in progress and probably isn't something most people will care to know is there

TODO for myself:
-Remove the question mark regarding nerdtree tabs
-Comfirm that vim-polyglot is for syntax highlighting
-Usage for fzf

### CODE REVIEW

**Comment by avelino** [comment]
Important information is to say what technology uses, has specific plugin for each technology

**Comment by nbelakovski** [comment]
I think I understand what you're saying. You think there should be a feature list, with references to the plugin that implements the feature as necessary?

**Comment by robsonpeixoto** [comment]
IMO the best way to learn how to use it is reading the code. Add this README info will add the cost of keeping it in sync.

**Comment by jtemporal** [comment]
> IMO the best way to learn how to use it is reading the code.

I disagree. Since not all that use vim-bootstrap want to have to read the code to find things out **and** not all are used to the syntax well enough to rapidly identify what does what.

Maybe we shouldn't add the list to the readme though. First we have a lot of info there already making it too long and as @robsonpeixoto said _add the cost of keeping it in sync._

**Comment by avelino** [comment]
I'm closing this PR because the cost of keeping synchronized will be very large.

We can go back to talk about this subject in an issue (if you deem it necessary), for this we need a proposal with synchronization

**Pull request closed without merging**
