### PR TITLE
Fix airline tabline icons and undefined or ugly symbols

### PR DESCRIPTION
**Pull request by di3goleite**
Before:
Airline before

After:
Airline after

### CODE REVIEW

**Comment by avelino** [comment]
warning after install:

    The variable g:airline_branch_prefix is deprecated and may not work in the future. It has been replaced with g:airline_symbols.branch. Please read the documentation....

**Comment by di3goleite** [comment]
@avelino , I fix this warning after read the airline documentation. Thanks.  ;)

**Comment by lerrua** [comment]
Guys, this pull request broken some special chars for Terminal users.


Maybe airline.vim have some dependencies for fix this unicode error, vim-bootstrap must be easy to install, without config steps.
I prefer something generic that works for everyone instead of something beautiful that works for very few people.

**Comment by lerrua** [comment]
If anyone have problem with this, please let me know.

**Comment by di3goleite** [comment]
@lerrua , thanks for report this. This problem happens because you don't have Powerline fonts installed in your terminal. If you to install [Menslo Powerline Font](https://github.com/powerline/fonts), for example, and use this font in your terminal... This problem is solved.

I agree with you and I prefer an generic approach.

**Pull request merged**
