### PR TITLE
set avelino fork repo official vim-bootstrap-updater package

### PR DESCRIPTION
**Pull request by avelino**
more than 1 year was opened a PR and we had no return of the @sherzberg
so I decided to keep a fork of official (thus keeping the credit of creator)
PR: https://github.com/sherzberg/vim-bootstrap-updater/pull/4 by @nemith
Accept PR in: https://github.com/avelino/vim-bootstrap-updater/commits/master

### CODE REVIEW

**Comment by sherzberg** [comment]
Sorry, I would be happy to point my readme to yours if you are comfortable with support this.

**Comment by avelino** [comment]
@sherzberg Rename the repository, you can already transfer for me

**Comment by sherzberg** [comment]
@avelino I can transfer if you remove your fork.

**Comment by avelino** [comment]
@sherzberg done

**Comment by sherzberg** [comment]
@avelino i started the transfer

**Comment by avelino** [comment]
done, thanks

**Comment by lerrua** [comment]
@avelino @sherzberg maybe vim-bootstrap-updater can be a package inside vim-bootstrap repository. What do you guys think about this?
`NeoBundle avelino/vim-bootstrap/vim-bootstrap-updater`

**Comment by avelino** [comment]
can do, so I've updated the readme that Eva repository

**Pull request merged**
