### PR TITLE
check vim version before attempting vimshell install

### PR DESCRIPTION
**Pull request by LISTERINE**

### CODE REVIEW

**Comment by lerrua** [comment]
@LISTERINE Just vim-shell doesn't work on vim 7.2?

**Comment by LISTERINE** [comment]
The only error I received when running it in 7.2 was from vimshell. There may be others that don't work, but once vimshell was excluded vim started without forcing me to acknowledge anything.

**Comment by lerrua** [comment]
@LISTERINE thanks for send this pull request ;)

**Comment by avelino** [comment]
+1

**Comment by LISTERINE** [comment]
Thanks for letting me contribute. I really love vim bootstrap; it's a staple for me on a new system.

**Comment by avelino** [comment]
Welcome to the collaboration team of vim-bootstrap, you came to add value!

**Pull request merged**
