### PR TITLE
Vim plug

### PR DESCRIPTION
**Pull request by cassiobotaro**
Replace Neobundle with Vim-Plug

Problems until now:
- [x] A substitute for NeoBundleCheck
- [x] vimproc make on windows
- [x] vim bootstrap update (can besolved with a python3 branch on vim_bootsttrap_updater)

### CODE REVIEW

**Comment by avelino** [comment]
+1

**Comment by lerrua** [comment]
Great job @cassiobotaro 🍺 

So, vim-plug has options to upgrade and automatic install and some options in the [faq](https://github.com/junegunn/vim-plug/wiki/faq). 

We can live without NeoBundleCheck.
About vimproc, we can write a solution in viml or use your solution (i need to test and i'm so sorry for windows users).

**Comment by cassiobotaro** [comment]
https://github.com/avelino/vim-bootstrap-updater/pull/6 can help to finnish this PR.

**Comment by avelino** [comment]
What's missing in this issue?

**Comment by cassiobotaro** [comment]
Now, only doc new plugin manager. I will do it in this week.

**Comment by lucasmezencio** [comment]
I can not wait for this PR to be merged! 😃

**Comment by avelino** [comment]
My tests it worked, did you manage to test @lerrua

**Comment by lerrua** [comment]
🚀

**Pull request merged**
