### PR TITLE
added editorconfig plugin to editorconfig.org support

### PR DESCRIPTION
**Pull request by raelmax**

### CODE REVIEW

**Comment by avelino** [comment]
I lke editorconfig plugin!
@lerrua What do you think that entering the core?

**Comment by raelmax** [comment]
It's very useful if you have to switch by the different projects and languages.

**Comment by lerrua** [comment]
We use vim-polyglot for some defaults by different languages, maybe for very different projects this can be useful. I'll test it. Thanks for the tip @raelmax

**Comment by hmleal** [comment]
I think is better define defaults for language in every flavor file. vim-polyglot define some strange defaults like html using tabs over spaces.

**Pull request closed without merging**
